name: scraper

on:
  pull_request:
    branches:
      - master
        #  schedule:
        #- cron: '0 */6 * * *'

jobs:
  scrape-to-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: |
          ./utils/iok.sh setup_py
      - name: Set up node
        run: |
          ./utils/iok.sh setup_node
      - name: Get full graph to json
        run: |
          source iok.vars
          echo "::set-env name=SCRAPED_CID::$ROOT_CID"
          ./utils/iok.sh get_graph $ROOT_CID > graph.json
      - name: Linearize graph to awesome list
        working-directory: python
        run: |
          pipenv run python3 -m scraper --file ../graph.json --out ../README.md
      - name: Show README
        run: |
          cat README.md
      - name: Add and commit
        if: ${{ github.event_name != 'pull_request' }}
        uses: EndBug/add-and-commit@v4
        with:
          add: README.md
          author_name: 🐦 IoK Bot
          author_email: birdie@iok.com
          message: Auto-generated from IOK ${{ env.SCRAPED_CID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
